server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/furkansahin91/cloud
          username: furkansahin91
          password: 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
